---

- name: define distribution-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install packages
  import_tasks: install.yml

- name: setup and configure irods
  import_tasks: setup_irods.yml

# - name: TODO -- what exactly does this do?
#   import_tasks: change_core.re.yml

# - import_tasks: transport_encryption.yml
#   when: inventory_hostname == irods_icat_server

# - import_tasks: transport_encryption.yml
#   when: inventory_hostname != irods_icat_server
