---

- name: Converge
  hosts: all
  pre_tasks:
    # package setup
    - name: update package repository (Debian)
      apt: update_cache=true
      when: ansible_os_family == "Debian"
      changed_when: false  # hack for idempotency
    - name: update package repository (Red Hat)
      yum: update_cache=true
      when: ansible_os_family == "RedHat"
      changed_when: false  # hack for idempotency
    - name: install netstat (Debian/Red Hat)
      package: name=net-tools state=present
      when: >
        ansible_os_family == "Debian" or
        ansible_os_family == "RedHat"
    # postgres setup
    - name: install postgres
      include_role:
        name: geerlingguy.postgresql
      # vars:
      # postgresql_hba_entries:
      #   - {type: local, database: all, user: postgres, auth_method: peer}
      #   - {type: local, database: all, user: all, auth_method: peer}
      #   - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
      #   - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}
    - name: restart postgresql
      systemd: name=postgresql state=restarted
      changed_when: false  # hack
    - name: create postgres user
      # for some reason, postgresql_user model fails in peer authentication
      shell: |
        set -eo pipefail
        sudo -u postgres createuser irods-test -w -s -d
        sudo -u postgres \
          psql -c \
          "ALTER USER \"irods-test\" WITH ENCRYPTED PASSWORD 'irods-test';"
        sudo -u postgres createdb -O irods-test -E UTF-8 -l en_US.UTF-8 -T template0 \
          irods-test
        touch /root/.pg_user_created
      args:
        executable: /bin/bash
        creates: /root/.pg_user_created
  vars:
    # bihealth.ssl_certs ------------------------------------------------------
    ssl_certs_certs:
      - name: instance
    # bihealth.postgres_client ------------------------------------------------
    postgres_client_host: 127.0.0.1
    postgres_client_db: irods-test
    postgres_client_user: irods-test
    postgres_client_password: irods-test
    # bihealth.irods_server ---------------------------------------------------
    irods_zone_name: testZone
    irods_password_salt: password_salt
    irods_negotiation_key: 12345678901234567890123456789012  # 32 bytes
    irods_zone_key: zone_key
    irods_control_plane_key: 12345678901234567890123456789012  # 32 bytes
    irods_rods_password: rods_password
  roles:
    - role: ansible-role-irods-server
